### ISSUE TITLE
Documentation ideas

### ISSUE THREAD

**Issue by Dboingue** [AngeloD2022/OnHubDesktop#1]
Since I am curious about your methods, and would like to understand the structure of your repository, I have made one fork, where I can make mistakes without affecting this workspace of yours.
I understand that your work is not about documentation, and that it is a lost art (I don't claim to ever have been a practitioner, but in my CS language courses I was taught about documenting and commenting.  Not a critic, more of an offer, to let you do what you do best.  But, I would like to follow your progress and understand the maximum I can.  So I will be writing issues about my experience with your repository, and my attempts at understanding and building its intended application on my local machine.  Is that a good plan.  I will leave some links here from time to time, about issues, I would like you to look at regarding my difficulties.  Is that ok, as well?

Also, I am learning the whole collaboration thing as I go.  I do have another slow project about documentation, that also is an indirect consequence of  my needs to use what I have to document.

I like issues for discussions, because they are editable, and part of the Github mechanics.

**Comment by AngeloD2022** [comment]
We are working on documentation right now, actually. But please reserve the issues tab for real bugs and things that need fixing or documenting. Thanks!

**Comment by Dboingue** [comment]
no problem.  I did fork so that I can use issues as I wanted.  your 
issues will only be about "bugs"

If i encounter difficulties building the software, do you prefer I use 
the reddit forum? for that?

I am going to install Qt locally. The project is open source through and 
through right.  Qt kind of confused me...  with its mixtures.

glad to hear about the doc.  I assume that some pages might appear in 
the repo wiki, from time to time... right.
I look forward understanding what you have done by examining the code 
and the documentation.

thanks and I wish you good work on that project.

Le 19/04/2020 à 15:37, Angelo D a écrit :
