### ISSUE TITLE
A few things that crash the app

### ISSUE THREAD

**Issue by isak-dombestein** [AngeloD2022/OnHubDesktop#8]
I'll get right to it:

I just compiled the OnHubDesktop app on my MacBook running macOS Big Sur 11.1 (Build 20C69) using qmake in qt5 which all went through perfectly fine and loads the app without any issues and keeps it at the "loading" phase until a signin has occured I assume. 

However, a few things that I have noticed:
- Clicking "Devices" while not signed in closes the app immediately
- Opening the SignIn window crashes the application completely.

I've seen through earlier issues that the OAuth client has been cause of issues for other users and although I don't really have any knowledge with C++, I'm willing to try my best to help troubleshoot and resolve these issues.

**Comment by AngeloD2022** [comment]
Got it. Thank you for reporting this! I'll update you on the status for the fix.

**Comment by AngeloD2022** [comment]
Just wanted to keep you updated: these will all be fixed in the `rewrite` branch.
